// Regenerates src/lib/test-count.generated.ts with the current number of test
// cases in the suite, so the /about page's "tests" metric stays live (queried
// at build, not hand-maintained). Source test files aren't included in the
// deployed serverless bundle, so this is captured at build time instead.
//
// Wired into `pnpm build`; run manually with `pnpm count-tests`.
import { readdirSync, readFileSync, writeFileSync, statSync } from "node:fs"
import { join, dirname } from "node:path"
import { fileURLToPath } from "node:url"

const root = join(dirname(fileURLToPath(import.meta.url)), "..")
const srcDir = join(root, "src")

/** @param {string} dir */
function testFiles(dir) {
  const out = []
  for (const name of readdirSync(dir)) {
    const full = join(dir, name)
    if (statSync(full).isDirectory()) {
      out.push(...testFiles(full))
    } else if (/\.test\.tsx?$/.test(name)) {
      out.push(full)
    }
  }
  return out
}

let count = 0
for (const file of testFiles(srcDir)) {
  const src = readFileSync(file, "utf-8")
  const matches = src.match(/(^|[^.\w])(it|test)\s*\(/g)
  count += matches ? matches.length : 0
}

const banner = "// AUTO-GENERATED by scripts/count-tests.mjs — do not edit by hand."
const body = `${banner}\nexport const TEST_COUNT = ${count}\n`
writeFileSync(join(srcDir, "lib", "test-count.generated.ts"), body)
console.log(`test-count.generated.ts → TEST_COUNT = ${count}`)
